---
- name: Run Database Container
  docker_container:
    name: database
    image: manon223/tp-devops-database:latest
    state: started
    restart_policy: always
    networks:
      - name: my_app_network
    env:
      POSTGRES_DB: "{{ vault_database_name }}"
      POSTGRES_USER: "{{ vault_database_user }}"
      POSTGRES_PASSWORD: "{{ vault_database_password }}"
    pull: true