---
# tasks file for roles/database
- name: Run database container
  docker_container:
    name: database
    image: manon223/tp-devops-database:latest
    env:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: db
    networks:
      - name: my_app_network
    restart_policy: always