- hosts: all
  become: true
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    docker_python_interpreter: /opt/docker_venv/bin/python

  roles:
    - docker
    - network
    - database
    - app
    - frontend
    - proxy
