- name: Run proxy container
  docker_container:
    name: my_proxy
    image: manon223/tp-devops-httpd:latest
    ports:
      - "80:80"
    networks:
      - name: my_app_network
    restart_policy: always