name: CI devops 2025

on:
  #to begin you want to launch this job in main and develop
  push:
    branches:
      - master
      - develop
  pull_request:

#liste les taches du pipeline
jobs:
  test-backend:
    runs-on: ubuntu-24.04
    steps:
    #checkout your github code using actions/checkout@v4
      - uses: actions/checkout@v4
      #do the same with another action (actions/setup-java@v4) that enable to setup jdk 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      #finally build your app with the latest command
      - name: Build and test with Maven
        run: mvn clean verify
        working-directory: ./backend/simpleapi

  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend/simpleapi
          file: ./backend/simpleapi/Dockerfile      # facultatif si Dockerfile s'appelle Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-backend:latest
          push: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}

      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          context: ./bdd           # ou ./dbb si c'est ton dossier
          file: ./bdd/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest
          push: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}

      - name: Build image and push httpd
        uses: docker/build-push-action@v6
        with:
          context: ./web
          file: ./web/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
          push: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
